### PR TITLE
Website Finishes

### PR DESCRIPTION
**Pull request by steelmaker86**
Finished as much as the website as I could. I feel fairly satisfied.

### CODE REVIEW

**Review by nevrending — CHANGES_REQUESTED** [review]
Thank you very much for your contribution!
Before doing an in-depth review of the PR, I'd like to highlight the following requests:
1. Can you rebase your fork from the latest `master`?
General Instructions: https://medium.com/@topspinj/how-to-git-rebase-into-a-forked-repo-c9f05e821c8a
2. Seems like the entire repo content was accidentally copied into `.github` folder. Can you please remove them?

Thanks!

**Comment by steelmaker86** [comment]
I think I solved most of the issues. 
In the meantime I added a few changes to the main page and community page, such as adding the art canvas. 

I wasn't exactly sure what to do with the From1st announcements section so I removed it. If you want you can add it back.

**Comment by steelmaker86** [comment]
I added a few extra changes such as adding the art canvas to the main page and community page. I also removed the announcements section because I wasn't exactly sure what to do with it. Adding it back would be fine if you want.
I also rebased it and removed the copy in .github.

**Review by nevrending — APPROVED** [review]
Thanks! I'll merge this to a new branch and make some changes before merging it to master.

**Pull request merged**
